# Generated by Django 3.2.5 on 2021-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Without title', max_length=50, verbose_name='Title')),
                ('intro', models.CharField(max_length=200, verbose_name='Intro')),
                ('whole_text', models.TextField(verbose_name='Article')),
                ('published_date', models.DateTimeField(verbose_name='Date of publish')),
            ],
        ),
    ]
