# Generated by Django 3.2.5 on 2021-07-31 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='published_date',
        ),
        migrations.AddField(
            model_name='articles',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of create'),
        ),
    ]
